# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='projectid',
            field=models.CharField(default='primenos', max_length=50),
        ),
    ]
