# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbms', '0002_subtask_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(default='cosmopal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
