# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_projects_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
