# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_auto_20161121_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbms.UserProfile'),
        ),
    ]
