# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_subtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
