# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_auto_20161121_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectid',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='dbms.Project'),
        ),
    ]
