# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_project_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='userprofiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='dbms.UserProfile'),
        ),
    ]
