# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20161122_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='projectid',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
