# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20161118_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='dbms.Project'),
        ),
    ]
