# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0007_auto_20161118_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='userprofiles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(to='dbms.Project'),
        ),
    ]
