# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(default=None, max_length=20)),
                ('project_name', models.CharField(default=None, max_length=20)),
                ('project_desc', models.TextField(default=None)),
                ('project_type', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.Projects'),
        ),
    ]
