# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0008_auto_20161123_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='result',
            field=models.CharField(default=b'0', max_length=100),
        ),
    ]
