# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0009_auto_20161129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='result',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
