# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0008_auto_20161118_1755'),
        ('dbms', '0010_auto_20161118_2115'),
    ]

    operations = [
    ]
